"""empty message

Revision ID: d8ea7ac63fcd
Revises: 
Create Date: 2021-07-04 17:17:18.939851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ea7ac63fcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('cnpjcpf', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proutos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=20), nullable=True),
    sa.Column('valor_unitario', sa.Float(precision=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proutos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
